'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'
'     このファイルへの変更は、正しくない動作の原因となる場合があります。
'     コードの再生成時には変更が失われます。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SiteMaster

    '''<summary>
    '''MainContent コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナー ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents MainContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
